services:
  apache:
    container_name: my-app-phpap # кастомное имя для удобства
    image: php:7.2-apache # образ php с установленным apache
    restart: unless-stopped # устанавливаем политику перезапуска контейнера
    ports:
      - "80:80" # проброс портов
    volumes:
      - ./website:/var/www/html # монтируем папку с html файлами в контейнер